### ISSUE TITLE
Update reminder

### ISSUE THREAD

**Issue by lolisa** [thzt/thzt.github.io#1]
Can you make a new issue or pull merge or release when you update your blog? I enjoy reading it.

**Comment by thzt** [comment]
I just wrote an article "Quotation in lisp", welcome exchange correction.

**Comment by thzt** [comment]
and one aricle about polymorphism of ">>=" function in Monad type class.

**Comment by lolisa** [comment]
thx.

**Comment by thzt** [comment]
another blog about the relationship of closures and objects is posted.
